# services/python/python-service.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-service
  template:
    metadata:
      labels:
        app: python-service
    spec:
      containers:
        - name: python-service
          image: python-service:latest
          ports:
            - containerPort: 8000
