apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  selector:
    app: postgresql-service
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
